name: FF14
version: 0.1
api-version: 1.17
main: potato.ball.ff14.Main
author: PotatoBaller
commands:
  ff:
    description: FinalFantasy Command
    usage: /<command>
    default: true
  stats:
    description: FinalFantasy Command
    usage: /<command>
    default: true
  jobchange:
    aliases: [changejob,jc]
    description: FinalFantasy Command
    usage: /<command>
    default: true